### ISSUE TITLE
Port for Dart

### ISSUE THREAD

**Issue by y4m4h4** [saketjajoo/Vaahan#1]
I’d like to implement a simple search for vehicle owner details (with auto captcha) via vahan.nic.in/nrservices/faces/user/searchstatus.xhtml or parivahan.gov.in/rcdlstatus in my flutter project. Is it possible to use Firebase ML for faster processing of vehicle image?

**Comment by saketjajoo** [comment]
@y4m4h4 
Sure. Firebase ML has pre-built models for computer vision. You can use them in your app; if not, you can build your custom model, deploy and use it. I do think it would be fast in terms of processing. You may also refer to [this link](https://github.com/azihsoyn/flutter_mlkit)
